# Prefix
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# Vi mode for copy
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# Split
unbind %
unbind '"'
bind _ split-window -v -c "#{pane_current_path}"
bind - split-window -h -c "#{pane_current_path}"
bind x kill-pane

# Session
bind k kill-window
bind P switch-client -p
bind N switch-client -n

# Switch Pane with <prefix> + Vim directions 
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# General
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"
set -g mouse on # Enable Mouse
set -g base-index 1 # Windows numbers start at 1
set -g pane-base-index 1 # Pane numbers start at 1
set -g renumber-windows on # re-number all windows when any is closed
set -g history-limit 50000
set -g escape-time 0
set -g focus-events on
set -g set-clipboard on
set -g allow-passthrough on
setw -g aggressive-resize on
set -g detach-on-destroy off

# Status bar
set -g status-position top
set -g status-interval 5
set -g status-left-length 30
set -g status-right-length 50
set -g window-status-separator ""
set -gw automatic-rename on
set -gw automatic-rename-format '#{b:pane_current_path}'

bind-key -r g run-shell "tmux neww lazygit" # Open lazygit in a new window
bind-key -r D run-shell "tmux neww lazydocker" # Open lazygit in a new window
bind-key -r f run-shell "tmux neww ~/.config/tmux/tmux-sessionizer" # Open tmux-sessionizer when <prefix> + f is pressed

# Plugins 
set -g @plugin 'tmux-plugins/tpm' # Plugin manager
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank' # Copy to system clipboard in tmux

# Theme
set -g status-style "bg=default,fg=default"
set -g status-left "#[fg=black,bg=blue,bold] #S #[bg=default] "
set -g status-right "#[fg=blue]#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=brightblack]#h "
set -g window-status-format "#[fg=brightblack] #I:#W "
set -g window-status-current-format "#[fg=blue,bold] #I:#W "
set -g pane-border-style "fg=brightblack"
set -g pane-active-border-style "fg=blue"
set -g message-style "bg=default,fg=blue"
set -g message-command-style "bg=default,fg=blue"
set -g mode-style "bg=blue,fg=black"
setw -g clock-mode-colour blue
